[package]
name = "pen"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "pen"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
lazy_static = "1.5"
home = "0.5.9"
